### ISSUE TITLE
Any plans for Ligature's ?

### ISSUE THREAD

**Issue by the-real-adammork** [Workshape/icon-font-generator#12]
Wondering if this is in the works or been considered previously. Thanks

**Comment by tancredi** [comment]
Hi @the-real-adammork - can you expand on this please? :)

**Comment by the-real-adammork** [comment]
Ligatures is a font feature that traditionally collapses 'ae' or 'fi' from two characters to one. It can be used to collapse 'facebook' to one character. Takes alot of pain out of the process because you dont need to templatize the unicode characters after compiling the icon font. 

I ended up grabbing the latest version of https://github.com/sunflowerdeath/webfonts-generator and ligature support is included. I call it directly and this solved my issue.

**Comment by tancredi** [comment]
No reason to close this - I would still consider implementing it on this repo as well

**Comment by the-real-adammork** [comment]
Ok, and you sit ontop of webfonts-generator so it should be pretty straightforward. Ill try and take a crack at it later today.

**Comment by tancredi** [comment]
That would be great, I'm gonna struggle finding time to look at it for a few days - just make sure to test that it works if you wanna open a pull request - thanks :)

**Comment by Kaishiyoku** [comment]
How is the status of this feature request?

**Comment by BrunnerLivio** [comment]
I was able to work around this!
Seems like the underlying library [sunflowerdeath/webfonts-generator](https://github.com/sunflowerdeath/webfonts-generator) has added support for ligatures a long time ago.
Unfortunately, the author of the repository forgot to update the package on NPM. The repository is now read-only and therefore we can't submit issues for that.
To work around this, we can use a specific commit of the Github repository in NPM like so

`package.json`
```json
{
  "dependencies": {
     "webfonts-generator": "sunflowerdeath/webfonts-generator#ed306cd"
  }
}
```

In order to correctly reference your icon font, you must use a custom CSS template. (Inspired by Material Design Icons)

`template/css.hbs`
```css
@font-face {
  font-family: "{{ fontName }}";
  font-style: normal;
  font-weight: 400;
  src: {{{ src }}};
}

{{ baseSelector }} {
  font-family: "{{ fontName }}";
  font-weight: normal;
  font-style: normal;
  font-size: 24px;  /* Preferred icon size */
  display: inline-block;
  line-height: 1;
  text-transform: none;
  letter-spacing: normal;
  word-wrap: normal;
  white-space: pre;
  direction: ltr;

  /* Support for all WebKit browsers. */
  -webkit-font-smoothing: antialiased;
  /* Support for Safari and Chrome. */
  text-rendering: optimizeLegibility;

  /* Support for Firefox. */
  -moz-osx-font-smoothing: grayscale;

  /* Support for IE. */
  font-feature-settings: 'liga';
}
```

`template/html.hbs`
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ fontName }}</title>

    <style>
        body {
            font-family: sans-serif;
            margin: 0;
            padding: 10px 20px;
            text-align: center;
        }
        .preview {
            width: 100px;
            display: inline-block;
            margin: 10px;
        }
        .preview .inner {
            display: inline-block;
            width: 100%;
            text-align: center;
            background: #f5f5f5;
            -webkit-border-radius: 3px 3px 0 0;
            -moz-border-radius: 3px 3px 0 0;
            border-radius: 3px 3px 0 0;
        }
        .preview .inner {{ baseTag }} {
            line-height: 85px;
            font-size: 40px;
            color: #333;
        }
        .label {
            display: inline-block;
            width: 100%;
            box-sizing: border-box;
            padding: 5px;
            font-size: 10px;
            font-family: Monaco, monospace;
            color: #666;
            white-space: nowrap;
            overflow: hidden;
            text-overflow: ellipsis;
            background: #ddd;
            -webkit-border-radius: 0 0 3px 3px;
            -moz-border-radius: 0 0 3px 3px;
            border-radius: 0 0 3px 3px;
            color: #666;
        }
    </style>

    <link rel="stylesheet" type="text/css" href="{{ htmlCssRelativePath }}" />
</head>
<body>

    <h1>{{ fontName }}</h1>

    {{# each names }}

        <div class="preview">
            <span class="inner">
                <{{ ../baseTag }} class="{{ ../baseClassNames }}">{{ this }}</{{ ../baseTag }}>
            </span>
            <br>
            <span class="label">{{ this }}</span>
        </div>

    {{/ each }}

</body>
</html>
```

I execute it like this
```bash
icon-font-generator --htmltp template/html.hbs \
  --csstp template/css.hbs \
  -o dist \
  icons/*.svg
```

---

I think the easiest way to fix this issue properly, is by forking [sunflowerdeath/webfonts-generator](https://github.com/sunflowerdeath/webfonts-generator) and maintain it properly. Personally I am not quite sure whether I want to maintain it myself due to time consumption. If anyone would like to volunteer, I would love to help though.
From `icon-font-generator` side of things, I would love to see a `--ligature` parameter, which will simply use the CSS and HTML template from above.
