### ISSUE TITLE
Why automatically add hash value to query string parameter? 

### ISSUE THREAD

**Issue by lion-man44** [Workshape/icon-font-generator#14]
I think it's better to can choose filename or query string parameter.

Expected:
```css
@font-face {
    font-family: "iconfonts";
    src: url("/assets/user/fonts/iconfonts-948840510a5a8a2d0f12d57c1067ebd7.eot") format("embedded-opentype"),
url("/assets/user/fonts/iconfonts-948840510a5a8a2d0f12d57c1067ebd7.woff2") format("woff2"),
url("/assets/user/fonts/iconfonts-948840510a5a8a2d0f12d57c1067ebd7.woff") format("woff"),
url("/assets/user/fonts/iconfonts-948840510a5a8a2d0f12d57c1067ebd7.ttf") format("truetype"),
url("/assets/user/fonts/iconfonts-948840510a5a8a2d0f12d57c1067ebd7.svg") format("svg");
}
```
