### ISSUE TITLE
--prefix does't seem to work

### ISSUE THREAD

**Issue by jaysalvat** [Workshape/icon-font-generator#31]
Hello and thanks for your work.

I've upgraded from 1.2 to the last version and my fonts are broken because I used --prefix i and now it doesn't seem to have any effect.

    icon-font-generator ./icons/icon-font/*.svg -o ./src/assets/fonts --prefix i --tag i

Generate CSS like:

```css
i {
    line-height: 1;
}

i[class^="icon-"]:before, i[class*=" icon-"]:before {
```

What am I missing? :)
Thanks in advance.

PS. I've read the changelog.
